In [1]:
import pandas as pd

In [3]:
import pandas as pd

df = pd.read_csv("/content/titanic.csv")
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
# syntax for loc
#df.loc[row_condition, column_selection]

In [5]:
df[df["Age"]>30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
df.loc[df["Age"] > 30, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# Passengers who survived
df.loc[df["Survived"] == 1, ["Name","Age","Survived"]]

                                                  Name   Age  Survived
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                               Heikkinen, Miss. Laina  26.0         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0         1
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0         1
..                                                 ...   ...       ...
875                   Najib, Miss. Adele Kiamie "Jane"  15.0         1
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0         1
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0         1
887                       Graham, Miss. Margaret Edith  19.0         1
889                              Behr, Mr. Karl Howell  26.0         1

[342 rows x 3 columns]

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
#Passengers in 1st class
df.loc[df["Pclass"]==1,["Name","Age","Pclass","Sex"]]

                                                  Name   Age  Pclass     Sex
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1  female
6                              McCarthy, Mr. Timothy J  54.0       1    male
11                            Bonnell, Miss. Elizabeth  58.0       1  female
23                        Sloper, Mr. William Thompson  28.0       1    male
..                                                 ...   ...     ...     ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0       1  female
872                           Carlsson, Mr. Frans Olof  33.0       1    male
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0       1  female
887                       Graham, Miss. Margaret Edith  19.0       1  female
889                              Behr, Mr. Karl Howell  26.0       1    male

[216 rows x 4 columns]

In [ ]:
# Age > 30 AND Survived
df.loc[(df["Age"] > 30) & (df["Survived"] == 0), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
# Age < 18 OR Female

In [ ]:
# make a 5 question  live and practice

In [ ]:
# find out the members numbers  of 3rd class who is female
df.loc[(df["Pclass"]==3) & (df["Sex"]=="female"),["Pclass","Sex","Name"]]

     Pclass     Sex                                               Name
2         3  female                             Heikkinen, Miss. Laina
8         3  female  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10        3  female                    Sandstrom, Miss. Marguerite Rut
14        3  female               Vestrom, Miss. Hulda Amanda Adolfina
18        3  female  Vander Planke, Mrs. Julius (Emelia Maria Vande...
..      ...     ...                                                ...
863       3  female                  Sage, Miss. Dorothy Edith "Dolly"
875       3  female                   Najib, Miss. Adele Kiamie "Jane"
882       3  female                       Dahlberg, Miss. Gerda Ulrika
885       3  female               Rice, Mrs. William (Margaret Norton)
888       3  female           Johnston, Miss. Catherine Helen "Carrie"

[144 rows x 3 columns]

In [ ]:
# find out the members numbers  of 3rd class who is male

In [ ]:
# Female passengers older than 25
df.loc[(df["Sex"] == "female") & (df["Age"] > 25), ["Name", "Age", "Pclass"]]

                                                  Name   Age  Pclass
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1
2                               Heikkinen, Miss. Laina  26.0       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0       3
11                            Bonnell, Miss. Elizabeth  58.0       1
..                                                 ...   ...     ...
866                       Duran y More, Miss. Asuncion  27.0       2
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0       1
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0       2
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0       1
885               Rice, Mrs. William (Margaret Norton)  39.0       3

[139 rows x 3 columns]

In [ ]:
# Female passengers older than 25

In [ ]:
# Average age of survivors
df.loc[df["Survived"]==1,"Age"].mean()

np.float64(28.343689655172415)

In [17]:
#Rich passengers (Fare > 100) who survived only find name and age

In [ ]:
# find the name and age of Children (<15) in 3rd class

In [ ]:
# Count passengers older than 60
df.loc[df["Age"] > 60, :].shape[0]

In [ ]:
# your task take a another datasets and make a 30 to 50 question and do a practcie like this