In [1]:
# 1️⃣ Import Pandas Library
# Import pandas to work with DataFrames
import pandas as pd

In [2]:
# 2️⃣ Create a Sample DataFrame
# We will create a DataFrame with columns 'Name', 'Age', 'City'
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar']
}

df = pd.DataFrame(data)  # Create DataFrame
df

      Name  Age        City
0    Alice   25   Kathmandu
1      Bob   30     Pokhara
2  Charlie   35    Lalitpur
3    David   40  Biratnagar

In [3]:
# 3️⃣ Default Index
# By default, Pandas assigns a numeric index starting from 0
print(df.index)  # Shows the default index

RangeIndex(start=0, stop=4, step=1)

# 4️⃣ Set a Column as Index

In [17]:
df.set_index("Name")

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

permanently set index

In [19]:
df.set_index("Name",inplace=True)

In [20]:
df

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

In [21]:
# 6️⃣ Reset Index

df.reset_index()

      Name  Age        City
0    Alice   25   Kathmandu
1      Bob   30     Pokhara
2  Charlie   35    Lalitpur
3    David   40  Biratnagar

In [ ]:
# 6️⃣ Reset Index

df.reset_index(inplace=True)

### What does inplace=True mean?

- `inplace=True` means **modify the original DataFrame**
- No new DataFrame is created
- Changes happen **permanently**

### Example:
Without inplace:
```python
new_df = df.set_index("Student_ID")

In [24]:
import pandas as pd
# Creating a simple DataFrame
data = {
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

# Display the DataFrame
df

   Student_ID  Name  Marks
0         101   Ram     85
1         102  Sita     90
2         103  Hari     78
3         104  Gita     92

In [26]:
df.set_index("Student_ID")

            Name  Marks
Student_ID
101          Ram     85
102         Sita     90
103         Hari     78
104         Gita     92

In [ ]:
df.set_index("Student_ID", inplace=True)

In [ ]:
df

            Name  Marks
Student_ID
101          Ram     85
102         Sita     90
103         Hari     78
104         Gita     92

task create a one data and practcie all like make index reset test with inplace